package com.abnormalities.config;

import net.minecraftforge.common.ForgeConfigSpec;

public class AbnormalitiesConfig {
    public enum PunishMode { KICK, CRASH, NONE }

    private static boolean configLoaded = false;
    public static final ForgeConfigSpec SPEC;
    public static final ForgeConfigSpec.IntValue GRACE_PERIOD_DAYS;
    public static final ForgeConfigSpec.IntValue NUR_SPAWN_WEIGHT;
    public static final ForgeConfigSpec.DoubleValue NUR_CURSOR_TRIGGER_DISTANCE;
    public static final ForgeConfigSpec.BooleanValue NUR_WATER;
    public static final ForgeConfigSpec.BooleanValue NUR_LAVA;
    public static final ForgeConfigSpec.BooleanValue NUR_LIQUID;
    public static final ForgeConfigSpec.BooleanValue NUR_BREAK_BLOCKS;
    public static final ForgeConfigSpec.BooleanValue NUR_BREAK_DROPS;
    public static final ForgeConfigSpec.BooleanValue NUR_TOWER;
    public static final ForgeConfigSpec.BooleanValue NUR_BRIDGE;
    public static final ForgeConfigSpec.IntValue NUR_SPEED_RAMP;
    public static final ForgeConfigSpec.IntValue NUR_MAX_SPEED_MULT;
    public static final ForgeConfigSpec.EnumValue<PunishMode> NUR_PUNISH;
    public static final ForgeConfigSpec.EnumValue<PunishMode> FRIEND_PUNISH;
    public static final ForgeConfigSpec.BooleanValue FRIEND_BREAK_BLOCKS;
    public static final ForgeConfigSpec.BooleanValue FRIEND_PLACE_BLOCKS;
    public static final ForgeConfigSpec.BooleanValue FRIEND_KILL_MOBS;
    public static final ForgeConfigSpec.BooleanValue FRIEND_REVIVE_MOBS;
    public static final ForgeConfigSpec.IntValue FRIEND_FOLLOW_TIME;
    public static final ForgeConfigSpec.IntValue FRIEND_SPAWN_WEIGHT;
    public static final ForgeConfigSpec.IntValue THE_MOTHER_SPAWN_WEIGHT;
    public static final ForgeConfigSpec.IntValue THE_MOTHER_MIN_WAIT;
    public static final ForgeConfigSpec.IntValue THE_MOTHER_MAX_WAIT;
    public static final ForgeConfigSpec.BooleanValue THE_MOTHER_STATIC_WAIT;
    public static final ForgeConfigSpec.IntValue THE_MOTHER_STATIC_WAIT_SECONDS;
    public static final ForgeConfigSpec.IntValue THE_MOTHER_MIN_ITEMS;
    public static final ForgeConfigSpec.IntValue THE_MOTHER_MAX_ITEMS;
    public static final ForgeConfigSpec.BooleanValue THE_MOTHER_STATIC_AMOUNT;
    public static final ForgeConfigSpec.IntValue THE_MOTHER_STATIC_ITEM_COUNT;
    public static final ForgeConfigSpec.BooleanValue THE_MOTHER_ONLY_VANILLA;
    public static final ForgeConfigSpec.IntValue THE_MOTHER_REWARD_COOKIES;
    public static final ForgeConfigSpec.IntValue THE_MOTHER_REWARD_GOLDEN_CARROTS;
    public static final ForgeConfigSpec.IntValue THE_MOTHER_REWARD_GOLDEN_APPLES;
    public static final ForgeConfigSpec.IntValue SW_SPAWN_WEIGHT;
    public static final ForgeConfigSpec.DoubleValue SW_APPROACH_SPEED;
    public static final ForgeConfigSpec.DoubleValue SW_DETECTION_RANGE;
    public static final ForgeConfigSpec.IntValue SW_TRANSFORM_TIME;
    public static final ForgeConfigSpec.IntValue SW_KILL_SPAWN_CHANCE;
    public static final ForgeConfigSpec.BooleanValue HORROR_EVENTS_ENABLED;
    public static final ForgeConfigSpec.DoubleValue HORROR_EVENT_HOSTILITY_FACTOR;
    public static final ForgeConfigSpec.BooleanValue SEGFAULT_ENABLED;
    public static final ForgeConfigSpec.IntValue SEGFAULT_SPAWN_WEIGHT;
    public static final ForgeConfigSpec.IntValue SEGFAULT_COOLDOWN_TICKS;
    public static final ForgeConfigSpec.IntValue SEGFAULT_GRACE_TICKS;
    public static final ForgeConfigSpec.IntValue SEGFAULT_WRONG_THRESHOLD;
    public static final ForgeConfigSpec.IntValue SEGFAULT_EVENT_DURATION;
    public static final ForgeConfigSpec.IntValue SEGFAULT_SWITCH_MIN;
    public static final ForgeConfigSpec.IntValue SEGFAULT_SWITCH_MAX;
    public static final ForgeConfigSpec.DoubleValue SEGFAULT_DAMAGE;
    public static final ForgeConfigSpec.DoubleValue SEGFAULT_MOVE_THRESHOLD;
    public static final ForgeConfigSpec.EnumValue<PunishMode> SEGFAULT_PUNISH;
    public static final ForgeConfigSpec.BooleanValue SEGFAULT_STARGAZED_ENABLED;
    public static final ForgeConfigSpec.IntValue SEGFAULT_STARGAZED_SPAWN_WEIGHT;
    public static final ForgeConfigSpec.IntValue SEGFAULT_STARGAZED_DURATION;
    public static final ForgeConfigSpec.IntValue SEGFAULT_STARGAZED_SWITCH_TICKS;
    public static final ForgeConfigSpec.IntValue SEGFAULT_STARGAZED_GRACE_TICKS;
    public static final ForgeConfigSpec.IntValue SEGFAULT_STARGAZED_WRONG_THRESHOLD;
    public static final ForgeConfigSpec.EnumValue<PunishMode> SEGFAULT_STARGAZED_PUNISH;
    public static final ForgeConfigSpec.BooleanValue V1S1T_ENABLED;
    public static final ForgeConfigSpec.IntValue V1S1T_INTERVAL;
    public static final ForgeConfigSpec.IntValue V1S1T_VISIT_DAYS;
    public static final ForgeConfigSpec.IntValue V1S1T_STAGE_UP;
    public static final ForgeConfigSpec.BooleanValue HUSH_ENABLED;
    public static final ForgeConfigSpec.IntValue HUSH_SPAWN_WEIGHT;
    public static final ForgeConfigSpec.IntValue HUSH_DURATION;
    public static final ForgeConfigSpec.IntValue HUSH_RANGE;
    public static final ForgeConfigSpec.IntValue HUSH_COOLDOWN;
    public static final ForgeConfigSpec.BooleanValue W4K3_ENABLED;
    public static final ForgeConfigSpec.IntValue W4K3_DISTANCE;
    public static final ForgeConfigSpec.IntValue W4K3_CHANCE;
    public static final ForgeConfigSpec.BooleanValue M1SL4Y_ENABLED;
    public static final ForgeConfigSpec.IntValue M1SL4Y_WEIGHT;
    public static final ForgeConfigSpec.BooleanValue L3NS_ENABLED;
    public static final ForgeConfigSpec.IntValue L3NS_CHANCE;
    public static final ForgeConfigSpec.IntValue L3NS_COOLDOWN;
    public static final ForgeConfigSpec.BooleanValue M1NER_ENABLED;
    public static final ForgeConfigSpec.IntValue M1NER_SPAWN_WEIGHT;
    public static final ForgeConfigSpec.IntValue M1NER_MAX_TUNNEL;
    public static final ForgeConfigSpec.IntValue M1NER_DUMMY_CHANCE;
    public static final ForgeConfigSpec.BooleanValue S1GN_ENABLED;
    public static final ForgeConfigSpec.IntValue S1GN_CHANCE;
    public static final ForgeConfigSpec.IntValue S1GN_INTERVAL;
    public static final ForgeConfigSpec.IntValue S1GN_SEARCH_RADIUS;
    public static final ForgeConfigSpec.BooleanValue BR34TH_ENABLED;
    public static final ForgeConfigSpec.IntValue BR34TH_CHANCE;
    public static final ForgeConfigSpec.BooleanValue H01D_ENABLED;
    public static final ForgeConfigSpec.IntValue H01D_THRESHOLD;
    public static final ForgeConfigSpec.BooleanValue C1RCL_ENABLED;
    public static final ForgeConfigSpec.IntValue C1RCL_CHANCE;
    public static final ForgeConfigSpec.BooleanValue F4DED_ENABLED;
    public static final ForgeConfigSpec.IntValue F4DED_CHANCE;
    public static final ForgeConfigSpec.BooleanValue FAKE_ACH_ENABLED;
    public static final ForgeConfigSpec.IntValue FAKE_ACH_COOLDOWN;
    public static final ForgeConfigSpec.BooleanValue HIM_ENABLED;
    public static final ForgeConfigSpec.IntValue HIM_SPAWN_WEIGHT;
    public static final ForgeConfigSpec.IntValue HIM_REP_MAX;
    public static final ForgeConfigSpec.EnumValue<PunishMode> HIM_PUNISH;
    public static final ForgeConfigSpec.BooleanValue F4K3_ENABLED;
    public static final ForgeConfigSpec.BooleanValue ANG3R_ENABLED;
    public static final ForgeConfigSpec.IntValue ANG3R_DURATION;
    public static final ForgeConfigSpec.BooleanValue B3D_ENABLED;

    public static final ForgeConfigSpec.BooleanValue HN_ENABLED;
    public static final ForgeConfigSpec.BooleanValue NUR_ENABLED;
    public static final ForgeConfigSpec.BooleanValue FRIEND_ENABLED;
    public static final ForgeConfigSpec.BooleanValue THE_MOTHER_ENABLED;
    public static final ForgeConfigSpec.BooleanValue SW_ENABLED;
    public static final ForgeConfigSpec.DoubleValue HN_GRACE_MULT;
    public static final ForgeConfigSpec.BooleanValue HN_PILLARS_ENABLED;
    public static final ForgeConfigSpec.IntValue HN_PILLARS_WIDTH;
    public static final ForgeConfigSpec.IntValue HN_PILLARS_DEPTH;
    public static final ForgeConfigSpec.IntValue HN_PILLARS_LENGTH;
    public static final ForgeConfigSpec.BooleanValue HN_PILLARS_RANDOM_SIZE;
    public static final ForgeConfigSpec.IntValue HN_PILLARS_RANDOM_MIN_W;
    public static final ForgeConfigSpec.IntValue HN_PILLARS_RANDOM_MAX_W;
    public static final ForgeConfigSpec.IntValue HN_PILLARS_RANDOM_MIN_D;
    public static final ForgeConfigSpec.IntValue HN_PILLARS_RANDOM_MAX_D;
    public static final ForgeConfigSpec.IntValue HN_PILLARS_RANDOM_MIN_L;
    public static final ForgeConfigSpec.IntValue HN_PILLARS_RANDOM_MAX_L;
    public static final ForgeConfigSpec.IntValue HN_PILLARS_SPEED;
    public static final ForgeConfigSpec.IntValue HN_PILLARS_HOUSE_CHANCE;
    public static final ForgeConfigSpec.IntValue HN_PILLARS_RANDOM_CHANCE;
    public static final ForgeConfigSpec.IntValue HN_PILLARS_DIRECT_CHANCE;
    public static final ForgeConfigSpec.IntValue HN_PILLARS_HOUSE_RADIUS;
    public static final ForgeConfigSpec.IntValue HN_PILLARS_HOUSE_CLUSTER;
    public static final ForgeConfigSpec.IntValue HN_PILLARS_STEAL_MIN;
    public static final ForgeConfigSpec.IntValue HN_PILLARS_STEAL_MAX;
    public static final ForgeConfigSpec.IntValue HN_PILLARS_COOLDOWN;
    public static final ForgeConfigSpec.BooleanValue HN_PILLARS_DUMP_INVENTORY;
    public static final ForgeConfigSpec.BooleanValue HN_PILLARS_BREAK_SOUNDS;
    public static final ForgeConfigSpec.IntValue HN_PILLARS_DAMAGE_RADIUS;
    public static final ForgeConfigSpec.IntValue HN_PILLARS_DAMAGE_AMOUNT;
    public static final ForgeConfigSpec.BooleanValue HN_SHAKE_ENABLED;
    public static final ForgeConfigSpec.DoubleValue HN_SHAKE_CRUSH;
    public static final ForgeConfigSpec.DoubleValue HN_SHAKE_DIRECT;
    public static final ForgeConfigSpec.IntValue HN_SHAKE_RANGE;
    public static final ForgeConfigSpec.BooleanValue HN_FURTHERLANDS_ENABLED;
    public static final ForgeConfigSpec.IntValue HN_FURTHERLANDS_COOLDOWN;
    public static final ForgeConfigSpec.IntValue HN_FURTHERLANDS_CHANCE;
    public static final ForgeConfigSpec.IntValue HN_FURTHERLANDS_RADIUS;
    public static final ForgeConfigSpec.IntValue HN_FURTHERLANDS_MAX_REP;

    public static final ForgeConfigSpec.BooleanValue HN_CHUNK_ENABLED;
    public static final ForgeConfigSpec.IntValue HN_CHUNK_RANGE;
    public static final ForgeConfigSpec.IntValue HN_CHUNK_CHANCE;
    public static final ForgeConfigSpec.IntValue HN_CHUNK_COOLDOWN;
    public static final ForgeConfigSpec.BooleanValue HN_BORDER_ENABLED;
    public static final ForgeConfigSpec.IntValue HN_BORDER_COOLDOWN;
    public static final ForgeConfigSpec.IntValue HN_BORDER_CHANCE;
    public static final ForgeConfigSpec.IntValue HN_BORDER_DISTANCE;

    public static final ForgeConfigSpec.BooleanValue PEAK_DAY_ENABLED;
    public static final ForgeConfigSpec.IntValue PEAK_DAY_BAD_CHANCE;
    public static final ForgeConfigSpec.IntValue PEAK_DAY_GOOD_CHANCE;
    public static final ForgeConfigSpec.IntValue PEAK_DAY_DURATION;
    public static final ForgeConfigSpec.DoubleValue PEAK_DAY_BAD_MULTIPLIER;
    public static final ForgeConfigSpec.DoubleValue PEAK_DAY_GOOD_MULTIPLIER;
    public static final ForgeConfigSpec.DoubleValue PEAK_DAY_BAD_SPAWN_MULT;
    public static final ForgeConfigSpec.DoubleValue PEAK_DAY_GOOD_SPAWN_MULT;
    public static final ForgeConfigSpec.IntValue PEAK_DAY_BAD_THE_MOTHER_MULT;
    public static final ForgeConfigSpec.IntValue PEAK_DAY_GOOD_THE_MOTHER_MULT;
    public static final ForgeConfigSpec.BooleanValue PEAK_DAY_WIND_DISABLED;
    public static final ForgeConfigSpec.IntValue PEAK_DAY_GIFT_INTERVAL;
    public static final ForgeConfigSpec.IntValue PEAK_DAY_MAX_GIFTS;

    public static final ForgeConfigSpec.BooleanValue CURSED_HOUSE_ENABLED;
    public static final ForgeConfigSpec.IntValue CURSED_HOUSE_DETECTION_RANGE;
    public static final ForgeConfigSpec.DoubleValue CURSED_HOUSE_CURSE_RATE;
    public static final ForgeConfigSpec.DoubleValue CURSED_HOUSE_DRAIN_RATE;
    public static final ForgeConfigSpec.DoubleValue CURSED_HOUSE_EVENT_MULT_MAX;
    public static final ForgeConfigSpec.DoubleValue CURSED_HOUSE_WIND_MULTIPLIER;

    public static final ForgeConfigSpec.BooleanValue CURSED_BIOME_ENABLED;
    public static final ForgeConfigSpec.IntValue CURSED_BIOME_MAX;
    public static final ForgeConfigSpec.IntValue CURSED_BIOME_CHANCE;
    public static final ForgeConfigSpec.IntValue CURSED_BIOME_CURSE_RATE;
    public static final ForgeConfigSpec.DoubleValue CURSED_BIOME_DRAIN_RATE;
    public static final ForgeConfigSpec.DoubleValue CURSED_BIOME_WIND_MULTIPLIER;
    public static final ForgeConfigSpec.IntValue CURSED_BIOME_HOSTILE_SPAWN_MULT;

    public static final ForgeConfigSpec.BooleanValue APPARITION_ENABLED;
    public static final ForgeConfigSpec.IntValue APPARITION_WEIGHT;
    public static final ForgeConfigSpec.IntValue APPARITION_MIN_REP;
    public static final ForgeConfigSpec.IntValue APPARITION_MAX_REP;
    public static final ForgeConfigSpec.IntValue APPARITION_SPAWN_RANGE;
    public static final ForgeConfigSpec.IntValue APPARITION_MAX_LIFETIME;

    public static final ForgeConfigSpec.BooleanValue B3DROCK_ENABLED;
    public static final ForgeConfigSpec.IntValue B3DROCK_CHANCE;
    public static final ForgeConfigSpec.IntValue B3DROCK_COOLDOWN;
    public static final ForgeConfigSpec.IntValue B3DROCK_MIN_SIZE;
    public static final ForgeConfigSpec.IntValue B3DROCK_MAX_SIZE;
    public static final ForgeConfigSpec.IntValue B3DROCK_MAX_REP;

    public static final ForgeConfigSpec.BooleanValue SIGN_ENABLED;
    public static final ForgeConfigSpec.IntValue SIGN_TIMER_MINUTES;
    public static final ForgeConfigSpec.IntValue SIGN_TELEPORT_CHANCE;
    public static final ForgeConfigSpec.IntValue SIGN_WAKE_CHANCE;
    public static final ForgeConfigSpec.IntValue SIGN_HIM_SPAWN_INTERVAL;
    public static final ForgeConfigSpec.IntValue SIGN_HIM_BATCH_SIZE;
    public static final ForgeConfigSpec.BooleanValue DEPTHS_ENABLED;
    public static final ForgeConfigSpec.IntValue DEPTHS_CHANCE;
    public static final ForgeConfigSpec.IntValue DEPTHS_RADIUS;
    public static final ForgeConfigSpec.BooleanValue DEPTHS_BREAK_BEDROCK;
    public static final ForgeConfigSpec.BooleanValue DISTANT_ENABLED;
    public static final ForgeConfigSpec.IntValue DISTANT_SPAWN_WEIGHT;
    public static final ForgeConfigSpec.IntValue HIM_SIGN_SPAWN_WEIGHT;

    static {
        ForgeConfigSpec.Builder b = new ForgeConfigSpec.Builder();
        GRACE_PERIOD_DAYS = b.comment("no spawns for this many days after world creation").defineInRange("gracePeriodDays", 3, 0, 100);
        b.push("nur");
        NUR_ENABLED = b.comment("enable nur entity (the shy stalker)").define("enabled", true);
        NUR_PUNISH = b.comment("punishment mode when nur kills you: KICK, CRASH, or NONE").defineEnum("onDeath", PunishMode.KICK);
        NUR_SPAWN_WEIGHT = b.comment("higher = rarer spawns at night").defineInRange("spawnWeight", 4000, 1, 100000);
        NUR_CURSOR_TRIGGER_DISTANCE = b.comment("how close cursor must be to hitbox to trigger chase").defineInRange("cursorTriggerDist", 0.5, 0.1, 3.0);
        NUR_WATER = b.comment("nur can walk on water by replacing it with stone").define("waterWalk", true);
        NUR_LAVA = b.comment("nur can walk on lava by replacing it with stone").define("lavaWalk", true);
        NUR_LIQUID = b.comment("nur can walk on any other liquid (modded fluids like create:honey) by replacing it with stone").define("liquidWalk", true);
        NUR_BREAK_BLOCKS = b.comment("nur can break blocks to reach you").define("breakBlocks", true);
        NUR_BREAK_DROPS = b.comment("broken blocks drop items").define("breakBlockDrops", false);
        NUR_TOWER = b.comment("nur can tower up to reach you").define("tower", true);
        NUR_BRIDGE = b.comment("nur can bridge horizontally to reach you").define("bridge", true);
        NUR_SPEED_RAMP = b.comment("blocks of distance per +1x chase speed (10 = +1x every 10 blocks)").defineInRange("speedRamp", 10, 1, 100);
        NUR_MAX_SPEED_MULT = b.comment("max chase speed multiplier at long distance").defineInRange("maxSpeedMult", 10, 1, 50);
        b.pop();
        configLoaded = true;
        b.push("friend");
        FRIEND_ENABLED = b.comment("enable friend entity (the clone that undoes your actions)").define("enabled", true);
        FRIEND_SPAWN_WEIGHT = b.comment("higher = rarer spawns").defineInRange("spawnWeight", 5000, 1, 1000000);
        FRIEND_PUNISH = b.comment("punishment when friend catches you: KICK, CRASH, or NONE").defineEnum("onCatch", PunishMode.KICK);
        FRIEND_BREAK_BLOCKS = b.comment("friend can undo block breaks").define("breakBlocks", true);
        FRIEND_PLACE_BLOCKS = b.comment("friend can undo block placements").define("placeBlocks", true);
        FRIEND_KILL_MOBS = b.comment("friend can undo mob kills").define("killMobs", true);
        FRIEND_REVIVE_MOBS = b.comment("friend can revive killed mobs").define("reviveMobs", true);
        FRIEND_FOLLOW_TIME = b.comment("seconds friend follows your path (default 10)").defineInRange("followTime", 10, 1, 60);
        b.pop();
        b.push("theMother");
        THE_MOTHER_ENABLED = b.comment("enable the Mother entity (the supplier that demands items)").define("enabled", true);
        THE_MOTHER_SPAWN_WEIGHT = b.comment("higher = rarer The Mother spawns").defineInRange("spawnWeight", 4000, 1, 100000);
        THE_MOTHER_MIN_WAIT = b.comment("minimum wait time in seconds for the mother item request").defineInRange("minWaitSeconds", 60, 5, 4096);
        THE_MOTHER_MAX_WAIT = b.comment("maximum wait time in seconds for the mother item request").defineInRange("maxWaitSeconds", 240, 5, 4096);
        THE_MOTHER_STATIC_WAIT = b.comment("use fixed wait time instead of random range").define("staticWaitTime", false);
        THE_MOTHER_STATIC_WAIT_SECONDS = b.comment("fixed the mother wait time in seconds (5-4096)").defineInRange("staticWaitSeconds", 120, 5, 4096);
        THE_MOTHER_MIN_ITEMS = b.comment("minimum item count requested from player").defineInRange("minItems", 1, 1, 64);
        THE_MOTHER_MAX_ITEMS = b.comment("maximum item count requested from player").defineInRange("maxItems", 32, 1, 64);
        THE_MOTHER_STATIC_AMOUNT = b.comment("use fixed item count instead of random range").define("staticAmount", false);
        THE_MOTHER_STATIC_ITEM_COUNT = b.comment("fixed item count when staticAmount is true (1-64)").defineInRange("staticItemCount", 4, 1, 64);
        THE_MOTHER_ONLY_VANILLA = b.comment("if true, the Mother only requests vanilla items (no modded items from tag)").define("onlyVanilla", true);
        THE_MOTHER_REWARD_COOKIES = b.comment("stack size of cookies given as reward").defineInRange("rewardCookies", 64, 1, 64);
        THE_MOTHER_REWARD_GOLDEN_CARROTS = b.comment("stack size of golden carrots given as reward").defineInRange("rewardGoldenCarrots", 32, 1, 64);
        THE_MOTHER_REWARD_GOLDEN_APPLES = b.comment("count of golden apples given as reward").defineInRange("rewardGoldenApples", 2, 1, 64);
        b.pop();
        b.push("skinwalker");
        SW_ENABLED = b.comment("enable skinwalker disguised mobs").define("enabled", true);
        SW_SPAWN_WEIGHT = b.comment("higher = rarer skinwalker spawns").defineInRange("spawnWeight", 4000, 1, 100000);
        SW_APPROACH_SPEED = b.comment("speed multiplier at which skinwalkers approach player (1.0 = the disguised animal's own speed)").defineInRange("approachSpeed", 1.0, 0.2, 2.0);
        SW_DETECTION_RANGE = b.comment("range at which skinwalkers detect players").defineInRange("detectionRange", 16.0, 8.0, 32.0);
        SW_TRANSFORM_TIME = b.comment("ticks within 2 blocks before transformation (240 = 12s)").defineInRange("transformTime", 240, 100, 600);
        SW_KILL_SPAWN_CHANCE = b.comment("percent chance to spawn nur on death").defineInRange("killSpawnChance", 75, 0, 100);
        b.pop();
        b.push("horror");
        HORROR_EVENTS_ENABLED = b.comment("enable psychological horror events").define("enabled", true);
        HORROR_EVENT_HOSTILITY_FACTOR = b.comment("global hostility factor for rep-based weight scaling").defineInRange("hostilityFactor", 1.0, 0.0, 3.0);
        b.pop();
        b.push("segfault");
        SEGFAULT_ENABLED = b.comment("enable segfault overlay events").define("enabled", true);
        SEGFAULT_SPAWN_WEIGHT = b.comment("higher = rarer natural spawns").defineInRange("spawnWeight", 4000, 1, 100000);
        SEGFAULT_COOLDOWN_TICKS = b.comment("ticks between segfault events (20 ticks = 1s)").defineInRange("cooldownTicks", 1200, 100, 72000);
        SEGFAULT_GRACE_TICKS = b.comment("ticks of grace after each state switch").defineInRange("graceTicks", 30, 5, 200);
        SEGFAULT_WRONG_THRESHOLD = b.comment("ticks of wrong behavior before punishment").defineInRange("wrongThreshold", 20, 1, 100);
        SEGFAULT_EVENT_DURATION = b.comment("max event duration in ticks").defineInRange("eventDuration", 300, 60, 1200);
        SEGFAULT_SWITCH_MIN = b.comment("minimum ticks between state switches").defineInRange("switchMin", 20, 5, 200);
        SEGFAULT_SWITCH_MAX = b.comment("maximum ticks between state switches").defineInRange("switchMax", 80, 10, 400);
        SEGFAULT_DAMAGE = b.comment("damage dealt on punishment").defineInRange("damage", 10.0, 1.0, 40.0);
        SEGFAULT_MOVE_THRESHOLD = b.comment("blocks/tick movement threshold (0.15 = walk speed)").defineInRange("moveThreshold", 0.15, 0.01, 1.0);
        SEGFAULT_PUNISH = b.comment("punishment for wrong move: KICK, CRASH, or NONE").defineEnum("onPunish", PunishMode.NONE);
        b.pop();
        b.push("segfaultStargazed");
        SEGFAULT_STARGAZED_ENABLED = b.comment("enable stargazed variant").define("enabled", true);
        SEGFAULT_STARGAZED_SPAWN_WEIGHT = b.comment("higher = rarer stargazed events").defineInRange("spawnWeight", 12000, 1, 100000);
        SEGFAULT_STARGAZED_DURATION = b.comment("max event duration in ticks").defineInRange("duration", 160, 40, 1200);
        SEGFAULT_STARGAZED_SWITCH_TICKS = b.comment("ticks between decisions (10 = 0.5s)").defineInRange("switchTicks", 10, 5, 60);
        SEGFAULT_STARGAZED_GRACE_TICKS = b.comment("grace after each switch").defineInRange("graceTicks", 15, 1, 60);
        SEGFAULT_STARGAZED_WRONG_THRESHOLD = b.comment("wrong ticks before punishment").defineInRange("wrongThreshold", 3, 1, 20);
        SEGFAULT_STARGAZED_PUNISH = b.comment("punishment for stargazed violation: KICK, CRASH, or NONE").defineEnum("onPunish", PunishMode.NONE);
        b.pop();
        b.push("v1s1t");
        V1S1T_ENABLED = b.comment("enable v1s1t home invasion events").define("enabled", true);
        V1S1T_INTERVAL = b.comment("game ticks between v1s1t visit checks (20 = 1s)").defineInRange("checkInterval", 6000, 200, 72000);
        V1S1T_VISIT_DAYS = b.comment("in-game days between visits").defineInRange("visitDays", 3, 1, 100);
        V1S1T_STAGE_UP = b.comment("total visits to advance one stage").defineInRange("stageUp", 3, 1, 20);
        b.pop();
        b.push("hush");
        HUSH_ENABLED = b.comment("enable hush events (mobs freeze and stare)").define("enabled", true);
        HUSH_SPAWN_WEIGHT = b.comment("higher = rarer hush events").defineInRange("spawnWeight", 4000, 1, 100000);
        HUSH_DURATION = b.comment("how long mobs freeze and stare (ticks, 20 = 1s)").defineInRange("duration", 400, 20, 800);
        HUSH_RANGE = b.comment("how far mobs are affected (blocks)").defineInRange("range", 64, 16, 128);
        HUSH_COOLDOWN = b.comment("ticks between hush events (20 = 1s)").defineInRange("cooldown", 3600, 200, 72000);
        b.pop();
        b.push("w4k3");
        W4K3_ENABLED = b.comment("enable waking up at different location").define("enabled", true);
        W4K3_DISTANCE = b.comment("minimum distance to teleport from bed (blocks)").defineInRange("distance", 60, 20, 200);
        W4K3_CHANCE = b.comment("1 in N chance when sleeping (higher = rarer)").defineInRange("chance", 3, 1, 100);
        b.pop();
        b.push("m1sl4y");
        M1SL4Y_ENABLED = b.comment("enable inventory misplacement (items shifting slots/stacks)").define("enabled", true);
        M1SL4Y_WEIGHT = b.comment("higher = rarer misplacement events").defineInRange("spawnWeight", 6000, 1, 100000);
        b.pop();
        b.push("l3ns");
        L3NS_ENABLED = b.comment("enable screenshot figure (figure appears in F2 screenshots)").define("enabled", true);
        L3NS_CHANCE = b.comment("1 in N screenshots get a figure (night only)").defineInRange("chance", 8, 2, 100);
        L3NS_COOLDOWN = b.comment("seconds between possible figure appearances").defineInRange("cooldown", 600, 60, 7200);
        b.pop();
        b.push("m1n3r");
        M1NER_ENABLED = b.comment("enable underground miner (carves tunnels near you)").define("enabled", true);
        M1NER_SPAWN_WEIGHT = b.comment("higher = rarer miner activity").defineInRange("spawnWeight", 6000, 1, 100000);
        M1NER_MAX_TUNNEL = b.comment("max blocks a tunnel can be carved").defineInRange("maxTunnelLength", 20, 5, 100);
        M1NER_DUMMY_CHANCE = b.comment("percent chance a dummy nur waits at tunnel end").defineInRange("dummyNurChance", 5, 0, 100);
        b.pop();
        b.push("s1gn");
        S1GN_ENABLED = b.comment("enable mysterious signs referencing your stats").define("enabled", true);
        S1GN_CHANCE = b.comment("1 in N checks place a sign").defineInRange("chance", 4000, 10, 100000);
        S1GN_INTERVAL = b.comment("min ticks between signs per player").defineInRange("interval", 12000, 600, 72000);
        S1GN_SEARCH_RADIUS = b.comment("block radius to search for sign spots").defineInRange("searchRadius", 12, 4, 32);
        b.pop();
        b.push("br34th");
        BR34TH_ENABLED = b.comment("enable phantom drowning (one tick of drown damage on dry land)").define("enabled", true);
        BR34TH_CHANCE = b.comment("1 in N checks trigger phantom drown").defineInRange("chance", 8000, 10, 100000);
        b.pop();
        b.push("h01d");
        H01D_ENABLED = b.comment("enable stillness detection (punishes standing still too long)").define("enabled", true);
        H01D_THRESHOLD = b.comment("ticks of stillness before trigger").defineInRange("threshold", 1200, 200, 7200);
        b.pop();
        b.push("c1rcl");
        C1RCL_ENABLED = b.comment("enable torch/campfire ring on wake").define("enabled", true);
        C1RCL_CHANCE = b.comment("1 in N wakes spawn a ring").defineInRange("chance", 5, 2, 100);
        b.pop();
        b.push("f4ded");
        F4DED_ENABLED = b.comment("enable block texture desync flicker (client-side)").define("enabled", true);
        F4DED_CHANCE = b.comment("1 in N checks flicker a block").defineInRange("chance", 60, 5, 1000);
        b.pop();
        b.push("fakeAch");
        FAKE_ACH_ENABLED = b.comment("enable fake black achievements (toast only, never in menu)").define("enabled", true);
        FAKE_ACH_COOLDOWN = b.comment("ticks between fake achievements").defineInRange("cooldown", 18000, 600, 240000);
        b.pop();
        b.push("him");
        HIM_ENABLED = b.comment("enable him, the player-like survivor that bridges and towers").define("enabled", true);
        HIM_SPAWN_WEIGHT = b.comment("base spawn weight at low nights (rarity rises with every boss kill)").defineInRange("spawnWeight", 8000, 1, 100000);
        HIM_REP_MAX = b.comment("him hunts the dangerous: only spawns if rep is BELOW this (low rep nights)").defineInRange("repMax", 999, 0, 2500);
        HIM_PUNISH = b.comment("punishment when he catches you: KICK, CRASH, or NONE").defineEnum("onDeath", PunishMode.KICK);
        b.pop();
        b.push("f4k3");
        F4K3_ENABLED = b.comment("enable fake chat messages (system chat with player names)").define("enabled", true);
        b.pop();
        b.push("ang3r");
        ANG3R_ENABLED = b.comment("enable chat anger system (insults trigger hostile replies)").define("enabled", true);
        ANG3R_DURATION = b.comment("duration of anger state in ticks").defineInRange("duration", 36000, 20, 720000);
        b.pop();
        b.push("b3d");
        B3D_ENABLED = b.comment("enable bed memory hunt (repeat sleep triggers nur spawn)").define("enabled", true);
        b.pop();

        b.push("0x0000");
        HN_ENABLED = b.comment("enable 0x0000 system (corruption, pillars, mimicry, lure)").define("enabled", true);
        HN_GRACE_MULT = b.comment("0x0000 events are X times rarer during grace period").defineInRange("gracePeriodMultiplier", 2.0, 1.0, 10.0);
        b.push("0x0000Pillars");
        HN_PILLARS_ENABLED = b.comment("enable 0x0000 pillar events (8x8 chunk destroyers)").define("enabled", true);
        HN_PILLARS_WIDTH = b.comment("pillar width in blocks").defineInRange("width", 8, 1, 32);
        HN_PILLARS_DEPTH = b.comment("pillar depth in blocks").defineInRange("depth", 8, 1, 32);
        HN_PILLARS_LENGTH = b.comment("pillar length (Y layers to descend)").defineInRange("length", 320, 16, 512);
        HN_PILLARS_RANDOM_SIZE = b.comment("randomize pillar dimensions (overrides width/depth/length)").define("randomSize", false);
        HN_PILLARS_RANDOM_MIN_W = b.comment("random width minimum").defineInRange("randomMinWidth", 4, 1, 32);
        HN_PILLARS_RANDOM_MAX_W = b.comment("random width maximum").defineInRange("randomMaxWidth", 16, 1, 32);
        HN_PILLARS_RANDOM_MIN_D = b.comment("random depth minimum").defineInRange("randomMinDepth", 4, 1, 32);
        HN_PILLARS_RANDOM_MAX_D = b.comment("random depth maximum").defineInRange("randomMaxDepth", 16, 1, 32);
        HN_PILLARS_RANDOM_MIN_L = b.comment("random length minimum").defineInRange("randomMinLength", 64, 16, 512);
        HN_PILLARS_RANDOM_MAX_L = b.comment("random length maximum").defineInRange("randomMaxLength", 320, 16, 512);
        HN_PILLARS_SPEED = b.comment("ticks per Y layer descent (1 = 20 blocks/sec, 5 = 4 blocks/sec)").defineInRange("speed", 1, 1, 20);
        HN_PILLARS_HOUSE_CHANCE = b.comment("percent chance pillar targets a detected house").defineInRange("houseTargetChance", 40, 0, 100);
        HN_PILLARS_RANDOM_CHANCE = b.comment("percent chance pillar spawns randomly around player").defineInRange("randomRingChance", 55, 0, 100);
        HN_PILLARS_DIRECT_CHANCE = b.comment("percent chance pillar spawns directly above player").defineInRange("directStrikeChance", 5, 0, 100);
        HN_PILLARS_HOUSE_RADIUS = b.comment("radius to scan for house blocks").defineInRange("houseScanRadius", 64, 16, 128);
        HN_PILLARS_HOUSE_CLUSTER = b.comment("minimum house blocks in proximity to count as a cluster").defineInRange("houseClusterSize", 5, 2, 20);
        HN_PILLARS_STEAL_MIN = b.comment("minimum inventory slots stolen on death").defineInRange("itemStealMin", 1, 0, 9);
        HN_PILLARS_STEAL_MAX = b.comment("maximum inventory slots stolen on death").defineInRange("itemStealMax", 4, 0, 9);
        HN_PILLARS_COOLDOWN = b.comment("ticks between pillar events").defineInRange("cooldown", 36000, 600, 720000);
        HN_PILLARS_DUMP_INVENTORY = b.comment("dump container contents when pillar destroys them").define("dumpInventory", true);
        HN_PILLARS_BREAK_SOUNDS = b.comment("play break sounds as pillar descends").define("breakSounds", true);
        HN_PILLARS_DAMAGE_RADIUS = b.comment("damage radius around pillar edge (blocks)").defineInRange("damageRadius", 2, 0, 8);
        HN_PILLARS_DAMAGE_AMOUNT = b.comment("damage dealt to players near pillar edge").defineInRange("damageAmount", 20, 1, 100);
        b.pop();
        b.push("0x0000Shake");
        HN_SHAKE_ENABLED = b.comment("enable screen shake on pillar impact").define("enabled", true);
        HN_SHAKE_CRUSH = b.comment("shake intensity when pillar crushes player").defineInRange("playerCrushIntensity", 3.0, 0.0, 5.0);
        HN_SHAKE_DIRECT = b.comment("shake intensity for direct strike").defineInRange("directStrikeIntensity", 4.0, 0.0, 5.0);
        HN_SHAKE_RANGE = b.comment("range where screen shake is felt (blocks)").defineInRange("range", 64, 16, 256);
        b.pop();
        b.push("0x0000Furtherlands");
        HN_FURTHERLANDS_ENABLED = b.comment("enable furtherlands (8-chunk radius, denser corruption, rarer than farlands)").define("enabled", true);
        HN_FURTHERLANDS_COOLDOWN = b.comment("ticks between furtherlands events (20 = 1s)").defineInRange("cooldown", 120000, 6000, 1200000);
        HN_FURTHERLANDS_CHANCE = b.comment("1 in N checks trigger furtherlands (higher = rarer)").defineInRange("chance", 20000, 1000, 100000);
        HN_FURTHERLANDS_RADIUS = b.comment("chunk radius of furtherlands generation").defineInRange("radius", 8, 4, 16);
        HN_FURTHERLANDS_MAX_REP = b.comment("players with rep above this never get furtherlands").defineInRange("maxRep", 800, 0, 2500);
        b.pop();
        b.push("0x0000Chunk");
        HN_CHUNK_ENABLED = b.comment("enable vertical chunk removal (massive terrain gash)").define("enabled", true);
        HN_CHUNK_RANGE = b.comment("max offset from player (blocks)").defineInRange("range", 64, 16, 256);
        HN_CHUNK_CHANCE = b.comment("1 in N checks trigger chunk removal (higher = rarer)").defineInRange("chance", 10000, 100, 100000);
        HN_CHUNK_COOLDOWN = b.comment("ticks between chunk removal events").defineInRange("cooldown", 60000, 600, 600000);
        b.pop();
        b.push("0x0000Border");
        HN_BORDER_ENABLED = b.comment("enable border (void ring around player at distance)").define("enabled", true);
        HN_BORDER_COOLDOWN = b.comment("ticks between border events (20 = 1s)").defineInRange("cooldown", 180000, 6000, 1800000);
        HN_BORDER_CHANCE = b.comment("1 in N checks trigger border (higher = rarer)").defineInRange("chance", 40000, 1000, 500000);
        HN_BORDER_DISTANCE = b.comment("chunk distance from player for the border ring").defineInRange("distance", 8, 4, 32);
        b.pop();
        b.pop();

        b.push("peakDay");
        PEAK_DAY_ENABLED = b.comment("enable peak day calendar system (BAD/GOOD/NORMAL day cycles)").define("enabled", true);
        PEAK_DAY_BAD_CHANCE = b.comment("percent chance a day is BAD (50% NORMAL, 25% BAD, 25% GOOD)").defineInRange("badChance", 25, 0, 100);
        PEAK_DAY_GOOD_CHANCE = b.comment("percent chance a day is GOOD").defineInRange("goodChance", 25, 0, 100);
        PEAK_DAY_DURATION = b.comment("how many consecutive BAD/GOOD days last").defineInRange("duration", 7, 1, 30);
        PEAK_DAY_BAD_MULTIPLIER = b.comment("horror event frequency multiplier on BAD days").defineInRange("badMultiplier", 2.0, 1.0, 10.0);
        PEAK_DAY_GOOD_MULTIPLIER = b.comment("horror event frequency multiplier on GOOD days").defineInRange("goodMultiplier", 0.3, 0.0, 1.0);
        PEAK_DAY_BAD_SPAWN_MULT = b.comment("entity spawn multiplier on BAD days (lower = more spawns)").defineInRange("badSpawnMult", 0.5, 0.01, 1.0);
        PEAK_DAY_GOOD_SPAWN_MULT = b.comment("entity spawn multiplier on GOOD days (higher = fewer spawns)").defineInRange("goodSpawnMult", 3.0, 1.0, 20.0);
        PEAK_DAY_BAD_THE_MOTHER_MULT = b.comment("The Mother item count multiplier on BAD days").defineInRange("badTheMotherMult", 2, 1, 10);
        PEAK_DAY_GOOD_THE_MOTHER_MULT = b.comment("The Mother item count multiplier on GOOD days").defineInRange("goodTheMotherMult", 1, 1, 10);
        PEAK_DAY_WIND_DISABLED = b.comment("0x0000 disabled on GOOD days").define("windDisabledOnGood", true);
        PEAK_DAY_GIFT_INTERVAL = b.comment("ticks between gift chest spawns on GOOD days").defineInRange("giftInterval", 300, 60, 3600);
        PEAK_DAY_MAX_GIFTS = b.comment("max gift chests per GOOD day").defineInRange("maxGifts", 3, 1, 20);
        b.pop();
        b.push("cursedHouse");
        CURSED_HOUSE_ENABLED = b.comment("enable cursed house system (houses accumulate curse over time)").define("enabled", true);
        CURSED_HOUSE_DETECTION_RANGE = b.comment("block radius to detect if player is in a house").defineInRange("detectionRange", 16, 4, 64);
        CURSED_HOUSE_CURSE_RATE = b.comment("curse level added per tick while player is in range").defineInRange("curseRate", 0.1, 0.01, 10.0);
        CURSED_HOUSE_DRAIN_RATE = b.comment("curse level drained per tick when player has enough rep").defineInRange("drainRate", 0.5, 0.01, 10.0);
        CURSED_HOUSE_EVENT_MULT_MAX = b.comment("max horror event multiplier near fully cursed house").defineInRange("eventMultMax", 2.0, 1.0, 10.0);
        CURSED_HOUSE_WIND_MULTIPLIER = b.comment("0x0000 corruption multiplier near cursed houses").defineInRange("windMultiplier", 2.0, 1.0, 10.0);
        b.pop();
        b.push("cursedBiome");
        CURSED_BIOME_ENABLED = b.comment("enable cursed biome system (biomes become corrupted over time)").define("enabled", true);
        CURSED_BIOME_MAX = b.comment("max cursed biomes active per player").defineInRange("maxCurses", 5, 1, 20);
        CURSED_BIOME_CHANCE = b.comment("1 in N checks curse a biome").defineInRange("chance", 100, 10, 10000);
        CURSED_BIOME_CURSE_RATE = b.comment("initial curse level when biome is cursed").defineInRange("curseRate", 100, 1, 1000);
        CURSED_BIOME_DRAIN_RATE = b.comment("curse level drained per tick when player has enough rep").defineInRange("drainRate", 0.3, 0.01, 10.0);
        CURSED_BIOME_WIND_MULTIPLIER = b.comment("0x0000 corruption multiplier in cursed biomes").defineInRange("windMultiplier", 2.0, 1.0, 10.0);
        CURSED_BIOME_HOSTILE_SPAWN_MULT = b.comment("hostile mob spawn multiplier in cursed biomes").defineInRange("hostileSpawnMult", 2, 1, 10);
        b.pop();
        b.push("apparition");
        APPARITION_ENABLED = b.comment("enable apparition jumpscares (entity appears then vanishes when looked at)").define("enabled", true);
        APPARITION_WEIGHT = b.comment("higher = rarer apparition spawns").defineInRange("spawnWeight", 2000, 100, 100000);
        APPARITION_MIN_REP = b.comment("minimum rep for apparitions to appear").defineInRange("minRep", 1200, 0, 2500);
        APPARITION_MAX_REP = b.comment("maximum rep for apparitions to appear").defineInRange("maxRep", 2500, 0, 2500);
        APPARITION_SPAWN_RANGE = b.comment("max distance from player to spawn apparition").defineInRange("spawnRange", 15, 5, 64);
        APPARITION_MAX_LIFETIME = b.comment("max apparition lifetime in ticks (300 = 15s, 6000 = 5min)").defineInRange("maxLifetime", 6000, 100, 12000);
        b.pop();
        b.push("b3drock");
        B3DROCK_ENABLED = b.comment("enable b3drock (giant bedrock cube event)").define("enabled", true);
        B3DROCK_CHANCE = b.comment("1 in N chance per check (1000000 = ultra rare, rarer than all events combined)").defineInRange("chance", 1000000, 100, 10000000);
        B3DROCK_COOLDOWN = b.comment("ticks between b3drock events (72000 = 1 hour)").defineInRange("cooldown", 72000, 600, 720000);
        B3DROCK_MIN_SIZE = b.comment("minimum width of the bedrock cube").defineInRange("minSize", 32, 8, 128);
        B3DROCK_MAX_SIZE = b.comment("maximum width of the bedrock cube").defineInRange("maxSize", 64, 8, 128);
        B3DROCK_MAX_REP = b.comment("players with rep above this never get b3drock").defineInRange("maxRep", 1250, 0, 2500);
        b.pop();
        b.push("sign");
        SIGN_ENABLED = b.comment("enable the sign dimension and related mechanics").define("enabled", true);
        SIGN_TIMER_MINUTES = b.comment("minutes before auto-return from sign dimension").defineInRange("timerMinutes", 2, 1, 120);
        SIGN_TELEPORT_CHANCE = b.comment("1 in N chance nur teleports you to sign instead of killing").defineInRange("teleportChance", 20, 1, 1000);
        SIGN_WAKE_CHANCE = b.comment("1 in N chance wake displacement sends you to sign").defineInRange("wakeChance", 50, 1, 1000);
        SIGN_HIM_SPAWN_INTERVAL = b.comment("ticks between himSign spawn batches in sign dimension").defineInRange("himSpawnInterval", 40, 10, 200);
        SIGN_HIM_BATCH_SIZE = b.comment("number of himSign entities per spawn batch").defineInRange("himBatchSize", 5, 1, 20);
        b.pop();
        b.push("himSign");
        HIM_SIGN_SPAWN_WEIGHT = b.comment("spawn weight for himSign in sign dimension (higher = rarer)").defineInRange("spawnWeight", 800, 1, 100000);
        b.pop();
        b.push("depths");
        DEPTHS_ENABLED = b.comment("enable the depths (water horror: blocks vanish, no swimming, pulled to void)").define("enabled", true);
        DEPTHS_CHANCE = b.comment("1 in N checks trigger depths when in water").defineInRange("chance", 200, 10, 10000);
        DEPTHS_RADIUS = b.comment("block radius of water removed under the player").defineInRange("radius", 8, 4, 32);
        DEPTHS_BREAK_BEDROCK = b.comment("depths breaks bedrock too").define("breakBedrock", true);
        b.pop();
        b.push("distant");
        DISTANT_ENABLED = b.comment("enable distant, the eyeless peripheral horror").define("enabled", true);
        DISTANT_SPAWN_WEIGHT = b.comment("higher = rarer distant spawns").defineInRange("spawnWeight", 3000, 100, 100000);
        b.pop();

        SPEC = b.build();
    }
}
