package com.abnormalities.config;

import net.minecraftforge.common.ForgeConfigSpec;

public class AbnormalitiesConfig {
    public enum PunishMode { KICK, CRASH, NONE }

    public static final ForgeConfigSpec SPEC;
    public static final ForgeConfigSpec.IntValue GRACE_PERIOD_DAYS;
    public static final ForgeConfigSpec.IntValue NUR_SPAWN_WEIGHT;
    public static final ForgeConfigSpec.DoubleValue NUR_CURSOR_TRIGGER_DISTANCE;
    public static final ForgeConfigSpec.BooleanValue NUR_WATER;
    public static final ForgeConfigSpec.BooleanValue NUR_LAVA;
    public static final ForgeConfigSpec.BooleanValue NUR_LIQUID;
    public static final ForgeConfigSpec.BooleanValue NUR_BREAK_BLOCKS;
    public static final ForgeConfigSpec.BooleanValue NUR_BREAK_DROPS;
    public static final ForgeConfigSpec.BooleanValue NUR_TOWER;
    public static final ForgeConfigSpec.BooleanValue NUR_BRIDGE;
    public static final ForgeConfigSpec.IntValue NUR_SPEED_RAMP;
    public static final ForgeConfigSpec.IntValue NUR_MAX_SPEED_MULT;
    public static final ForgeConfigSpec.EnumValue<PunishMode> NUR_PUNISH;
    public static final ForgeConfigSpec.EnumValue<PunishMode> K3W_PUNISH;
    public static final ForgeConfigSpec.BooleanValue K3W_BREAK_BLOCKS;
    public static final ForgeConfigSpec.BooleanValue K3W_PLACE_BLOCKS;
    public static final ForgeConfigSpec.BooleanValue K3W_KILL_MOBS;
    public static final ForgeConfigSpec.BooleanValue K3W_REVIVE_MOBS;
    public static final ForgeConfigSpec.IntValue K3W_FOLLOW_TIME;
    public static final ForgeConfigSpec.IntValue K3W_SPAWN_WEIGHT;
    public static final ForgeConfigSpec.IntValue XYZ_SPAWN_WEIGHT;
    public static final ForgeConfigSpec.IntValue XYZ_MIN_WAIT;
    public static final ForgeConfigSpec.IntValue XYZ_MAX_WAIT;
    public static final ForgeConfigSpec.BooleanValue XYZ_STATIC_WAIT;
    public static final ForgeConfigSpec.IntValue XYZ_STATIC_WAIT_SECONDS;
    public static final ForgeConfigSpec.IntValue XYZ_MIN_ITEMS;
    public static final ForgeConfigSpec.IntValue XYZ_MAX_ITEMS;
    public static final ForgeConfigSpec.BooleanValue XYZ_STATIC_AMOUNT;
    public static final ForgeConfigSpec.IntValue XYZ_STATIC_ITEM_COUNT;
    public static final ForgeConfigSpec.IntValue XYZ_REWARD_COOKIES;
    public static final ForgeConfigSpec.IntValue XYZ_REWARD_GOLDEN_CARROTS;
    public static final ForgeConfigSpec.IntValue XYZ_REWARD_GOLDEN_APPLES;
    public static final ForgeConfigSpec.IntValue SW_SPAWN_WEIGHT;
    public static final ForgeConfigSpec.DoubleValue SW_APPROACH_SPEED;
    public static final ForgeConfigSpec.DoubleValue SW_DETECTION_RANGE;
    public static final ForgeConfigSpec.IntValue SW_TRANSFORM_TIME;
    public static final ForgeConfigSpec.IntValue SW_KILL_SPAWN_CHANCE;
    public static final ForgeConfigSpec.BooleanValue HORROR_EVENTS_ENABLED;
    public static final ForgeConfigSpec.DoubleValue HORROR_EVENT_HOSTILITY_FACTOR;
    public static final ForgeConfigSpec.BooleanValue VR9P_ENABLED;
    public static final ForgeConfigSpec.IntValue VR9P_SPAWN_WEIGHT;
    public static final ForgeConfigSpec.IntValue VR9P_COOLDOWN_TICKS;
    public static final ForgeConfigSpec.IntValue VR9P_GRACE_TICKS;
    public static final ForgeConfigSpec.IntValue VR9P_WRONG_THRESHOLD;
    public static final ForgeConfigSpec.IntValue VR9P_EVENT_DURATION;
    public static final ForgeConfigSpec.IntValue VR9P_SWITCH_MIN;
    public static final ForgeConfigSpec.IntValue VR9P_SWITCH_MAX;
    public static final ForgeConfigSpec.DoubleValue VR9P_DAMAGE;
    public static final ForgeConfigSpec.DoubleValue VR9P_MOVE_THRESHOLD;
    public static final ForgeConfigSpec.EnumValue<PunishMode> VR9P_PUNISH;
    public static final ForgeConfigSpec.BooleanValue VR9P_STARGAZED_ENABLED;
    public static final ForgeConfigSpec.IntValue VR9P_STARGAZED_SPAWN_WEIGHT;
    public static final ForgeConfigSpec.IntValue VR9P_STARGAZED_DURATION;
    public static final ForgeConfigSpec.IntValue VR9P_STARGAZED_SWITCH_TICKS;
    public static final ForgeConfigSpec.IntValue VR9P_STARGAZED_GRACE_TICKS;
    public static final ForgeConfigSpec.IntValue VR9P_STARGAZED_WRONG_THRESHOLD;
    public static final ForgeConfigSpec.EnumValue<PunishMode> VR9P_STARGAZED_PUNISH;
    public static final ForgeConfigSpec.BooleanValue V1S1T_ENABLED;
    public static final ForgeConfigSpec.IntValue V1S1T_INTERVAL;
    public static final ForgeConfigSpec.IntValue V1S1T_VISIT_DAYS;
    public static final ForgeConfigSpec.IntValue V1S1T_STAGE_UP;
    public static final ForgeConfigSpec.BooleanValue HUSH_ENABLED;
    public static final ForgeConfigSpec.IntValue HUSH_SPAWN_WEIGHT;
    public static final ForgeConfigSpec.IntValue HUSH_DURATION;
    public static final ForgeConfigSpec.IntValue HUSH_RANGE;
    public static final ForgeConfigSpec.IntValue HUSH_COOLDOWN;
    public static final ForgeConfigSpec.BooleanValue W4K3_ENABLED;
    public static final ForgeConfigSpec.IntValue W4K3_DISTANCE;
    public static final ForgeConfigSpec.IntValue W4K3_CHANCE;
    public static final ForgeConfigSpec.BooleanValue M1SL4Y_ENABLED;
    public static final ForgeConfigSpec.IntValue M1SL4Y_WEIGHT;
    public static final ForgeConfigSpec.BooleanValue L3NS_ENABLED;
    public static final ForgeConfigSpec.IntValue L3NS_CHANCE;
    public static final ForgeConfigSpec.IntValue L3NS_COOLDOWN;
    public static final ForgeConfigSpec.BooleanValue M1NER_ENABLED;
    public static final ForgeConfigSpec.IntValue M1NER_SPAWN_WEIGHT;
    public static final ForgeConfigSpec.IntValue M1NER_MAX_TUNNEL;
    public static final ForgeConfigSpec.IntValue M1NER_DUMMY_CHANCE;
    public static final ForgeConfigSpec.BooleanValue LURE_ENABLED;
    public static final ForgeConfigSpec.IntValue LURE_SPAWN_WEIGHT;
    public static final ForgeConfigSpec.IntValue LURE_COOLDOWN;
    public static final ForgeConfigSpec.EnumValue<PunishMode> LURE_PUNISH;
    public static final ForgeConfigSpec.BooleanValue OTHER_ENABLED;
    public static final ForgeConfigSpec.IntValue OTHER_SPAWN_WEIGHT;
    public static final ForgeConfigSpec.IntValue OTHER_COOLDOWN;
    static {
        ForgeConfigSpec.Builder b = new ForgeConfigSpec.Builder();
        GRACE_PERIOD_DAYS = b.comment("no spawns for this many days after world creation").defineInRange("gracePeriodDays", 3, 0, 100);
        b.push("nur");
        NUR_PUNISH = b.comment("punishment mode when nur kills you: KICK, CRASH, or NONE").defineEnum("onDeath", PunishMode.KICK);
        NUR_SPAWN_WEIGHT = b.comment("higher = rarer spawns at night").defineInRange("spawnWeight", 200, 1, 10000);
        NUR_CURSOR_TRIGGER_DISTANCE = b.comment("how close cursor must be to hitbox to trigger chase").defineInRange("cursorTriggerDist", 0.5, 0.1, 3.0);
        NUR_WATER = b.comment("nur can walk on water by replacing it with stone").define("waterWalk", true);
        NUR_LAVA = b.comment("nur can walk on lava by replacing it with stone").define("lavaWalk", true);
        NUR_LIQUID = b.comment("nur can walk on any other liquid (modded fluids like create:honey) by replacing it with stone").define("liquidWalk", true);
        NUR_BREAK_BLOCKS = b.comment("nur can break blocks to reach you").define("breakBlocks", true);
        NUR_BREAK_DROPS = b.comment("broken blocks drop items").define("breakBlockDrops", false);
        NUR_TOWER = b.comment("nur can tower up to reach you").define("tower", true);
        NUR_BRIDGE = b.comment("nur can bridge horizontally to reach you").define("bridge", true);
        NUR_SPEED_RAMP = b.comment("blocks of distance per +1x chase speed (10 = +1x every 10 blocks)").defineInRange("speedRamp", 10, 1, 100);
        NUR_MAX_SPEED_MULT = b.comment("max chase speed multiplier at long distance").defineInRange("maxSpeedMult", 10, 1, 50);
        b.pop();
        b.push("k3w");
        K3W_SPAWN_WEIGHT = b.comment("higher = rarer spawns").defineInRange("spawnWeight", 200, 1, 100000);
        K3W_PUNISH = b.comment("punishment when k3w catches you: KICK, CRASH, or NONE").defineEnum("onCatch", PunishMode.KICK);
        K3W_BREAK_BLOCKS = b.comment("k3w can undo block breaks").define("breakBlocks", true);
        K3W_PLACE_BLOCKS = b.comment("k3w can undo block placements").define("placeBlocks", true);
        K3W_KILL_MOBS = b.comment("k3w can undo mob kills").define("killMobs", true);
        K3W_REVIVE_MOBS = b.comment("k3w can revive killed mobs").define("reviveMobs", true);
        K3W_FOLLOW_TIME = b.comment("seconds k3w follows your path (default 10)").defineInRange("followTime", 10, 1, 60);
        b.pop();
        b.push("xYz");
        XYZ_SPAWN_WEIGHT = b.comment("higher = rarer xyz spawns").defineInRange("spawnWeight", 400, 1, 10000);
        XYZ_MIN_WAIT = b.comment("minimum wait time in seconds for xyz item request").defineInRange("minWaitSeconds", 60, 5, 4096);
        XYZ_MAX_WAIT = b.comment("maximum wait time in seconds for xyz item request").defineInRange("maxWaitSeconds", 240, 5, 4096);
        XYZ_STATIC_WAIT = b.comment("use fixed wait time instead of random range").define("staticWaitTime", false);
        XYZ_STATIC_WAIT_SECONDS = b.comment("fixed xyz wait time in seconds (5-4096)").defineInRange("staticWaitSeconds", 120, 5, 4096);
        XYZ_MIN_ITEMS = b.comment("minimum item count requested from player").defineInRange("minItems", 1, 1, 64);
        XYZ_MAX_ITEMS = b.comment("maximum item count requested from player").defineInRange("maxItems", 32, 1, 64);
        XYZ_STATIC_AMOUNT = b.comment("use fixed item count instead of random range").define("staticAmount", false);
        XYZ_STATIC_ITEM_COUNT = b.comment("fixed item count when staticAmount is true (1-64)").defineInRange("staticItemCount", 4, 1, 64);
        XYZ_REWARD_COOKIES = b.comment("stack size of cookies given as reward").defineInRange("rewardCookies", 64, 1, 64);
        XYZ_REWARD_GOLDEN_CARROTS = b.comment("stack size of golden carrots given as reward").defineInRange("rewardGoldenCarrots", 32, 1, 64);
        XYZ_REWARD_GOLDEN_APPLES = b.comment("count of golden apples given as reward").defineInRange("rewardGoldenApples", 2, 1, 64);
        b.pop();
        b.push("skinwalker");
        SW_SPAWN_WEIGHT = b.comment("higher = rarer skinwalker spawns").defineInRange("spawnWeight", 400, 1, 10000);
        SW_APPROACH_SPEED = b.comment("speed at which skinwalkers approach player").defineInRange("approachSpeed", 0.25, 0.05, 0.5);
        SW_DETECTION_RANGE = b.comment("range at which skinwalkers detect players").defineInRange("detectionRange", 16.0, 8.0, 32.0);
        SW_TRANSFORM_TIME = b.comment("ticks within 2 blocks before transformation (240 = 12s)").defineInRange("transformTime", 240, 100, 600);
        SW_KILL_SPAWN_CHANCE = b.comment("percent chance to spawn nur on death").defineInRange("killSpawnChance", 75, 0, 100);
        b.pop();
        b.push("horror");
        HORROR_EVENTS_ENABLED = b.comment("enable psychological horror events").define("enabled", true);
        HORROR_EVENT_HOSTILITY_FACTOR = b.comment("global hostility factor for rep-based weight scaling").defineInRange("hostilityFactor", 1.0, 0.0, 3.0);
        b.pop();
        b.push("vr9p");
        VR9P_ENABLED = b.comment("enable vr9p overlay events").define("enabled", true);
        VR9P_SPAWN_WEIGHT = b.comment("higher = rarer natural spawns").defineInRange("spawnWeight", 400, 1, 10000);
        VR9P_COOLDOWN_TICKS = b.comment("ticks between vr9p events (20 ticks = 1s)").defineInRange("cooldownTicks", 1200, 100, 72000);
        VR9P_GRACE_TICKS = b.comment("ticks of grace after each state switch").defineInRange("graceTicks", 30, 5, 200);
        VR9P_WRONG_THRESHOLD = b.comment("ticks of wrong behavior before punishment").defineInRange("wrongThreshold", 20, 1, 100);
        VR9P_EVENT_DURATION = b.comment("max event duration in ticks").defineInRange("eventDuration", 300, 60, 1200);
        VR9P_SWITCH_MIN = b.comment("minimum ticks between state switches").defineInRange("switchMin", 20, 5, 200);
        VR9P_SWITCH_MAX = b.comment("maximum ticks between state switches").defineInRange("switchMax", 80, 10, 400);
        VR9P_DAMAGE = b.comment("damage dealt on punishment").defineInRange("damage", 10.0, 1.0, 40.0);
        VR9P_MOVE_THRESHOLD = b.comment("blocks/tick movement threshold (0.15 = walk speed)").defineInRange("moveThreshold", 0.15, 0.01, 1.0);
        VR9P_PUNISH = b.comment("punishment for wrong move: KICK, CRASH, or NONE").defineEnum("onPunish", PunishMode.KICK);
        b.pop();
        b.push("vr9pStargazed");
        VR9P_STARGAZED_ENABLED = b.comment("enable stargazed variant").define("enabled", true);
        VR9P_STARGAZED_SPAWN_WEIGHT = b.comment("higher = rarer stargazed events").defineInRange("spawnWeight", 1200, 1, 10000);
        VR9P_STARGAZED_DURATION = b.comment("max event duration in ticks").defineInRange("duration", 160, 40, 1200);
        VR9P_STARGAZED_SWITCH_TICKS = b.comment("ticks between decisions (10 = 0.5s)").defineInRange("switchTicks", 10, 5, 60);
        VR9P_STARGAZED_GRACE_TICKS = b.comment("grace after each switch").defineInRange("graceTicks", 15, 1, 60);
        VR9P_STARGAZED_WRONG_THRESHOLD = b.comment("wrong ticks before punishment").defineInRange("wrongThreshold", 3, 1, 20);
        VR9P_STARGAZED_PUNISH = b.comment("punishment for stargazed violation: KICK, CRASH, or NONE").defineEnum("onPunish", PunishMode.KICK);
        b.pop();
        b.push("v1s1t");
        V1S1T_ENABLED = b.comment("enable v1s1t home invasion events").define("enabled", true);
        V1S1T_INTERVAL = b.comment("game ticks between v1s1t visit checks (20 = 1s)").defineInRange("checkInterval", 6000, 200, 72000);
        V1S1T_VISIT_DAYS = b.comment("in-game days between visits").defineInRange("visitDays", 3, 1, 100);
        V1S1T_STAGE_UP = b.comment("total visits to advance one stage").defineInRange("stageUp", 3, 1, 20);
        b.pop();
        b.push("hush");
        HUSH_ENABLED = b.comment("enable hush events (mobs freeze and stare)").define("enabled", true);
        HUSH_SPAWN_WEIGHT = b.comment("higher = rarer hush events").defineInRange("spawnWeight", 400, 1, 10000);
        HUSH_DURATION = b.comment("how long mobs freeze and stare (ticks, 20 = 1s)").defineInRange("duration", 60, 20, 400);
        HUSH_RANGE = b.comment("how far mobs are affected (blocks)").defineInRange("range", 64, 16, 128);
        HUSH_COOLDOWN = b.comment("ticks between hush events (20 = 1s)").defineInRange("cooldown", 3600, 200, 72000);
        b.pop();
        b.push("w4k3");
        W4K3_ENABLED = b.comment("enable waking up at different location").define("enabled", true);
        W4K3_DISTANCE = b.comment("minimum distance to teleport from bed (blocks)").defineInRange("distance", 60, 20, 200);
        W4K3_CHANCE = b.comment("1 in N chance when sleeping (higher = rarer)").defineInRange("chance", 3, 1, 100);
        b.pop();
        b.push("m1sl4y");
        M1SL4Y_ENABLED = b.comment("enable inventory misplacement (items shifting slots/stacks)").define("enabled", true);
        M1SL4Y_WEIGHT = b.comment("higher = rarer misplacement events").defineInRange("spawnWeight", 600, 1, 10000);
        b.pop();
        b.push("l3ns");
        L3NS_ENABLED = b.comment("enable screenshot figure (figure appears in F2 screenshots)").define("enabled", true);
        L3NS_CHANCE = b.comment("1 in N screenshots get a figure (night only)").defineInRange("chance", 8, 2, 100);
        L3NS_COOLDOWN = b.comment("seconds between possible figure appearances").defineInRange("cooldown", 600, 60, 7200);
        b.pop();
        b.push("m1n3r");
        M1NER_ENABLED = b.comment("enable underground miner (carves tunnels near you)").define("enabled", true);
        M1NER_SPAWN_WEIGHT = b.comment("higher = rarer miner activity").defineInRange("spawnWeight", 600, 1, 10000);
        M1NER_MAX_TUNNEL = b.comment("max blocks a tunnel can be carved").defineInRange("maxTunnelLength", 20, 5, 100);
        M1NER_DUMMY_CHANCE = b.comment("percent chance a dummy nur waits at tunnel end").defineInRange("dummyNurChance", 5, 0, 100);
        b.pop();
        b.push("1ull");
        LURE_ENABLED = b.comment("enable the lure (music box that draws you in)").define("enabled", true);
        LURE_SPAWN_WEIGHT = b.comment("higher = rarer lure appearances").defineInRange("spawnWeight", 500, 1, 10000);
        LURE_COOLDOWN = b.comment("ticks between lure events (20 = 1s)").defineInRange("cooldown", 7200, 600, 72000);
        LURE_PUNISH = b.comment("punishment when lure catches you: KICK, CRASH, or NONE").defineEnum("onCatch", PunishMode.KICK);
        b.pop();
        b.push("0th3r");
        OTHER_ENABLED = b.comment("enable fake player (tab list shows someone who isn't there)").define("enabled", true);
        OTHER_SPAWN_WEIGHT = b.comment("higher = rarer fake player events").defineInRange("spawnWeight", 800, 1, 10000);
        OTHER_COOLDOWN = b.comment("ticks between fake player events (20 = 1s)").defineInRange("cooldown", 7200, 600, 72000);
        b.pop();
        SPEC = b.build();
    }
}
